import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
export function AccountDetailModal(props) {
    const { accountDetail, accountForm, setAccountForm, setAccountDetail, saveAccountDetail } = props;
    if (!accountDetail)
        return null;
    return (_jsx("div", { className: "modal-mask", onClick: () => setAccountDetail(null), children: _jsxs("div", { className: "modal-card", onClick: (e) => e.stopPropagation(), children: [_jsxs("h3", { children: ["\u8D26\u53F7\u8BE6\u60C5\u7F16\u8F91\uFF1A", accountDetail.username] }), _jsx("input", { placeholder: "\u7528\u6237\u540D", value: accountForm.username, onChange: (e) => setAccountForm({ ...accountForm, username: e.target.value }) }), _jsx("input", { placeholder: "\u5BC6\u7801", value: accountForm.password, onChange: (e) => setAccountForm({ ...accountForm, password: e.target.value }) }), _jsxs("select", { value: accountForm.role, onChange: (e) => setAccountForm({ ...accountForm, role: e.target.value }), children: [_jsx("option", { value: "user", children: "\u666E\u901A\u7528\u6237" }), _jsx("option", { value: "admin", children: "\u7BA1\u7406\u5458" })] }), _jsxs("select", { value: accountForm.status, onChange: (e) => setAccountForm({
                        ...accountForm,
                        status: e.target.value,
                    }), children: [_jsx("option", { value: "active", children: "active" }), _jsx("option", { value: "pending_review", children: "pending_review" }), _jsx("option", { value: "rejected", children: "rejected" })] }), _jsx("textarea", { placeholder: "\u5BA1\u6838\u5907\u6CE8", value: accountForm.reviewNote, onChange: (e) => setAccountForm({ ...accountForm, reviewNote: e.target.value }) }), _jsxs("div", { className: "row", children: [_jsx("button", { onClick: saveAccountDetail, children: "\u4FDD\u5B58\u4FEE\u6539" }), _jsx("button", { className: "ghost", onClick: () => setAccountDetail(null), children: "\u5173\u95ED" })] })] }) }));
}
export function ProductDetailModal(props) {
    const { detail, setDetail, favorites, toggleFavorite, user, contactSeller, messages, setMessageImageFile, messageInput, setMessageInput, sendMessage, } = props;
    if (!detail)
        return null;
    return (_jsx("div", { className: "modal-mask", onClick: () => setDetail(null), children: _jsxs("div", { className: "detail-modal", onClick: (e) => e.stopPropagation(), children: [_jsx("h3", { children: detail.title }), _jsx("div", { className: "detail-images", children: detail.images.map((img, i) => (_jsx("img", { src: img, alt: `图片${i + 1}` }, i))) }), _jsx("p", { children: detail.description }), _jsxs("p", { children: [_jsx("b", { children: "\u4EF7\u683C\uFF1A" }), "\u00A5", detail.price] }), _jsxs("p", { children: [_jsx("b", { children: "\u5730\u70B9\uFF1A" }), detail.campus] }), _jsxs("p", { children: [_jsx("b", { children: "\u5356\u5BB6\uFF1A" }), detail.sellerName] }), _jsxs("p", { children: [_jsx("b", { children: "\u53D1\u5E03\u65F6\u95F4\uFF1A" }), new Date(detail.createdAt).toLocaleString("zh-CN")] }), detail.category === "digital" && (_jsxs("p", { children: [_jsx("b", { children: "\u89C4\u683C\uFF1A" }), detail.brand, " / ", detail.model, " / ", detail.memory] })), _jsxs("div", { className: "row", children: [_jsx("button", { className: favorites.includes(detail.id) ? "small fav active" : "small fav", onClick: () => toggleFavorite(detail.id), children: favorites.includes(detail.id) ? "取消收藏" : "收藏商品" }), detail.sellerId !== user?.id && (_jsx("button", { className: "small contact-seller-btn", onClick: contactSeller, children: "\uD83D\uDCAC \u8054\u7CFB\u5356\u5BB6" })), _jsx("button", { className: "ghost", onClick: () => setDetail(null), children: "\u5173\u95ED" })] }), _jsx("hr", { style: { border: "none", borderTop: "1px solid #e2e8f0", margin: "12px 0" } }), _jsx("h4", { children: "\u8054\u7CFB\u5356\u5BB6 / \u7559\u8A00" }), _jsx("div", { className: "message-list", children: messages.map((m) => (_jsxs("div", { className: "message-item", children: [_jsx("b", { children: m.fromUsername }), _jsxs("span", { className: "muted", children: [" ", new Date(m.createdAt).toLocaleString("zh-CN")] }), m.content.includes("[图片:") ? (_jsx("div", { className: "message-content", children: m.content.split("\n").map((line, i) => line.startsWith("[图片:") ? (_jsx("img", { src: line.replace("[图片:", "").replace("]", "").trim(), alt: "\u7559\u8A00\u56FE\u7247", className: "chat-image" }, i)) : (_jsx("p", { children: line }, i))) })) : (_jsx("p", { children: m.content }))] }, m.id))) }), _jsx("input", { type: "file", accept: "image/*", onChange: (e) => setMessageImageFile(e.target.files?.[0] || null) }), _jsxs("div", { className: "row", children: [_jsx("input", { placeholder: "\u8F93\u5165\u7559\u8A00\u5185\u5BB9...", value: messageInput, onChange: (e) => setMessageInput(e.target.value) }), _jsx("button", { onClick: sendMessage, children: "\u53D1\u9001" })] })] }) }));
}
export function ChatModal(props) {
    const { chatTarget, setChatTarget, relatedProduct, setRelatedProduct, chatMessages, user, chatInput, setChatInput, setChatImageFile, sendChatMessage, } = props;
    if (!chatTarget)
        return null;
    return (_jsx("div", { className: "modal-mask", onClick: () => { setChatTarget(null); setRelatedProduct(null); }, children: _jsxs("div", { className: "chat-modal", onClick: (e) => e.stopPropagation(), children: [_jsxs("div", { className: "chat-header", children: [_jsxs("h3", { children: ["\u4E0E ", chatTarget.username, " \u5BF9\u8BDD"] }), relatedProduct && (_jsxs("div", { className: "related-product", children: [_jsx("img", { src: relatedProduct.images?.[0], alt: relatedProduct.title }), _jsxs("div", { children: [_jsx("b", { children: relatedProduct.title }), _jsxs("span", { children: ["\u00A5", relatedProduct.price] })] })] }))] }), _jsx("div", { className: "chat-messages", id: "chat-messages-container", children: chatMessages.length === 0 ? (_jsx("div", { className: "chat-empty", children: _jsx("p", { className: "muted", children: "\u6682\u65E0\u6D88\u606F\uFF0C\u5F00\u59CB\u5BF9\u8BDD\u5427\uFF01" }) })) : (chatMessages.map((m) => (_jsxs("div", { className: `chat-bubble ${m.fromUserId === user?.id ? "mine" : "other"}`, children: [_jsx("b", { children: m.fromUsername }), m.content.includes("[图片:") ? (_jsx("div", { className: "message-content", children: m.content.split("\n").map((line, i) => line.startsWith("[图片:") ? (_jsx("img", { src: line.replace("[图片:", "").replace("]", ""), alt: "\u56FE\u7247\u6D88\u606F", className: "chat-image" }, i)) : (_jsx("p", { children: line }, i))) })) : (_jsx("p", { children: m.content })), _jsx("span", { className: "muted", children: new Date(m.createdAt).toLocaleTimeString("zh-CN") })] }, m.id)))) }), _jsxs("div", { className: "chat-input-area", children: [_jsx("textarea", { placeholder: "\u8F93\u5165\u6D88\u606F...", value: chatInput, onChange: (e) => setChatInput(e.target.value), onKeyDown: (e) => {
                                if (e.key === "Enter" && !e.shiftKey) {
                                    e.preventDefault();
                                    sendChatMessage();
                                }
                            }, rows: 2 }), _jsx("div", { className: "image-input-row", children: _jsx("input", { type: "file", accept: "image/*", onChange: (e) => setChatImageFile(e.target.files?.[0] || null), className: "image-url-input" }) }), _jsx("button", { onClick: sendChatMessage, className: "send-btn", children: "\u53D1\u9001\u6D88\u606F" })] })] }) }));
}
